### ISSUE TITLE
`Cannot import name 'rank_zero_only'` and 502 error

### ISSUE THREAD

**Issue by cppietime** [slooi/NovelAI-Setup-Guide#2]
I followed the instructions in the README on Google Colab, and when running the server, the following error raised:

    ImportError: cannot import name 'rank_zero_only' from 'pytorch_lightning.utilities.distributed' (/content/naifu/venv/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py)

And when accessing the web page, the following was displayed:

    502 Bad Gateway
    Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared

**Comment by Redir1** [comment]
Caused by the PyTorch lightning version 1.80. Can be resolved through downgrade to 1.7.7
Change REQUIREMENT.TXT line 14 from “pytorch_lightning” to “pytorch_lightning==1.7.7”

**Comment by slooi** [comment]
It was caused by the pytorch_lightning update. I've set the pytorch_lightning to version 1.7.7 instead of using the latest version: [0b44925](https://github.com/slooi/ImageAI-Setup-Guide/commit/0b44925e12cfef69aff29a1f4ea32b0bd1890d9e)
It should work now.
